name: Save and Restore Windows Files

on:
  workflow_dispatch: # para rodar manualmente
  push:
    branches: [ main ]

jobs:
  prepare:
    runs-on: windows-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Baixar ou gerar arquivos
        run: |
          echo "Baixando arquivos grandes..."
          # Exemplo de download
          curl -L -o arquivo1.zip "https://exemplo.com/arquivo1.zip"
          curl -L -o arquivo2.zip "https://exemplo.com/arquivo2.zip"

      - name: Salvar arquivos como artifacts
        uses: actions/upload-artifact@v3
        with:
          name: meus-arquivos
          path: |
            arquivo1.zip
            arquivo2.zip

  use_saved_files:
    runs-on: windows-latest
    needs: prepare
    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Baixar arquivos salvos
        uses: actions/download-artifact@v3
        with:
          name: meus-arquivos
          path: ./meus-arquivos

      - name: Verificar arquivos
        run: |
          dir ./meus-arquivos
